media: src/images
content:
  - name: home
    path: src/index.md
    type: file
  - name: about
    path: src/about.md
    type: file
  - name: galleries
    path: src/galleries
    type: collection
    fields:
      - name: title
        label: Gallery title
        type: string
      - { name: layout, type: string, hidden: true, default: layouts/gallery.html }
      - name: images
        type: image
        list: true
        options:
          path: src/images
          extensions: [ jpg, jpeg, png ]