media: images
content:
  - name: home
    path: index.md
    type: file
  - name: about
    path: about.md
    type: file
  - name: galleries
    path: galleries
    type: collection
    fields:
      - name: title
        label: Gallery title
        type: string
      - { name: layout, type: string, hidden: true, default: layouts/gallery.html }
      - name: images
        type: object
        list: true
        fields:
          - name: src
            type: image
            options:
              path: images
              extensions: [ jpg, jpeg, png ]
          - name: alt
            type: string