media: images
content:
  - name: home
    path: index.md
    type: file
  - name: about
    path: about.md
    type: file
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, label: Key, type: string }
          - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
  - name: galleries
    path: galleries
    type: collection
    fields:
      - name: title
        label: Gallery title
        type: string
      - { name: layout, type: string, hidden: true, default: layouts/gallery.html }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, label: Key, type: string }
          - { name: order, label: Order, type: number }
      - name: images
        type: object
        list: true
        fields:
          - name: src
            type: image
            options:
              path: images
              extensions: [ jpg, jpeg, png ]
          - name: alt
            type: string